2023-10-08 16:15:44,735 INFO: Microblog startup [in D:\MyWork\Python\Flask\poetry-demo\app\__init__.py:74]
2023-10-08 16:15:47,132 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\MyWork\Python\Flask\poetry-demo\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "D:\MyWork\Python\Flask\poetry-demo\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\MyWork\Python\Flask\poetry-demo\app\models.py", line 36, in get_reset_password_token
    current_app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2023-10-08 16:22:55,008 INFO: Microblog startup [in D:\MyWork\Python\Flask\poetry-demo\app\__init__.py:74]
2023-10-08 16:23:02,852 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\MyWork\Python\Flask\poetry-demo\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "D:\MyWork\Python\Flask\poetry-demo\app\auth\email.py", line 26, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\MyWork\Python\Flask\poetry-demo\app\templates\email\reset_password.html", line 9, in top-level template code
    <p>{{ url_for('reset_password', token=token, _external=True) }}</p>
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2023-10-08 16:23:50,311 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\MyWork\Python\Flask\poetry-demo\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "D:\MyWork\Python\Flask\poetry-demo\app\auth\email.py", line 26, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\MyWork\Python\Flask\poetry-demo\app\templates\email\reset_password.html", line 9, in top-level template code
    <p>{{ url_for('reset_password', token=token, _external=True) }}</p>
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\asuka\AppData\Local\pypoetry\Cache\virtualenvs\app-ZkVP9aVc-py3.10\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2023-10-08 16:32:00,686 INFO: Microblog startup [in D:\MyWork\Python\Flask\poetry-demo\app\__init__.py:74]
